//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyPiggyStudent.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HappyPiggyStudent.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap Chat {
            get {
                object obj = ResourceManager.GetObject("Chat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка!.
        /// </summary>
        internal static string LoginWindow_Error {
            get {
                return ResourceManager.GetString("LoginWindow_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо выбрать ровно один сервер из списка..
        /// </summary>
        internal static string LoginWindow_OnlyOneServerError {
            get {
                return ResourceManager.GetString("LoginWindow_OnlyOneServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо ввести имя пользователя..
        /// </summary>
        internal static string LoginWindow_ShouldEnterUserName {
            get {
                return ResourceManager.GetString("LoginWindow_ShouldEnterUserName", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap MoneySection_small {
            get {
                object obj = ResourceManager.GetObject("MoneySection_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap news_small {
            get {
                object obj = ResourceManager.GetObject("news_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap news_small_new {
            get {
                object obj = ResourceManager.GetObject("news_small_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap piggy {
            get {
                object obj = ResourceManager.GetObject("piggy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap piggy_tr {
            get {
                object obj = ResourceManager.GetObject("piggy_tr", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap piggy1 {
            get {
                object obj = ResourceManager.GetObject("piggy1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка загрузки сценария &apos;prototype.ssml&apos;.
        /// </summary>
        internal static string PrototypeGameController_Scenario_load_error {
            get {
                return ResourceManager.GetString("PrototypeGameController_Scenario_load_error", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Stats_small {
            get {
                object obj = ResourceManager.GetObject("Stats_small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно покупать у себя.
        /// </summary>
        internal static string StudentMainWindow_BuyOwn {
            get {
                return ResourceManager.GetString("StudentMainWindow_BuyOwn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно выставить на продажу больше акций, чем у Вас есть.
        /// </summary>
        internal static string StudentMainWindow_cmdSell_TooManySharesError {
            get {
                return ResourceManager.GetString("StudentMainWindow_cmdSell_TooManySharesError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка.
        /// </summary>
        internal static string StudentMainWindow_Error {
            get {
                return ResourceManager.GetString("StudentMainWindow_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Недостаточно денег для покупки.
        /// </summary>
        internal static string StudentMainWindow_NotEnoughMoney {
            get {
                return ResourceManager.GetString("StudentMainWindow_NotEnoughMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Своё предложение] .
        /// </summary>
        internal static string StudentMainWindow_OwnOffer {
            get {
                return ResourceManager.GetString("StudentMainWindow_OwnOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  руб..
        /// </summary>
        internal static string StudentMainWindow_Rubles {
            get {
                return ResourceManager.GetString("StudentMainWindow_Rubles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ход .
        /// </summary>
        internal static string StudentMainWindow_Turn {
            get {
                return ResourceManager.GetString("StudentMainWindow_Turn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверное число акций или стоимость.
        /// </summary>
        internal static string StudentMainWindow_WrongShareNumber {
            get {
                return ResourceManager.GetString("StudentMainWindow_WrongShareNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  за .
        /// </summary>
        internal static string StudentMainWindow_Za {
            get {
                return ResourceManager.GetString("StudentMainWindow_Za", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невозможно выставить 0 акций на продажу.
        /// </summary>
        internal static string StudentMainWindow_ZeroShareNumberError {
            get {
                return ResourceManager.GetString("StudentMainWindow_ZeroShareNumberError", resourceCulture);
            }
        }
    }
}
